### ISSUE TITLE
Robot.c need reconstruction

### ISSUE THREAD

**Issue by WenzeJin** [spicyGrape/CCoursework-COMP0002#1]
重复的代码太多了 比如
1. Robot 前进的代码中有大量的与`TILE_WIDTH`换算相关的代码，是否可以包装到一个函数中
2. `left` 和 `right` 完全可以用类似以下的代码完成
```c
DIRECTION = ['N', 'E', 'S', 'W']
CURR_DIR = 0

void right() {
    CURR_DIR = (CURR_DIR + 1) % 4;
}

void left() {
    CURR_DIR = (CURR_DIR + 3) % 4;
}
```

**Comment by shuaiting-li** [comment]
Thanks for commenting! They are very good suggestions! I'll take it.

The whole project is currently in prototype stage. There do be many chunks that need further abstraction.

**Comment by WenzeJin** [comment]
🥳
